# Generated by Django 3.1.5 on 2021-01-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1011_auto_20210101_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetaDataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_string', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMetaDataFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metadata', to='documents.document')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.custommetadatafield')),
            ],
        ),
        migrations.CreateModel(
            name='CustomMetaDataFieldBooleanValue',
            fields=[
                ('value', models.BooleanField()),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='boolean', serialize=False, to='documents.custommetadatafieldvalue')),
            ],
            bases=('documents.custommetadatafieldvalue',),
        ),
        migrations.CreateModel(
            name='CustomMetaDataFieldShortTextValue',
            fields=[
                ('value', models.CharField(max_length=128)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='shorttext', serialize=False, to='documents.custommetadatafieldvalue')),
            ],
            bases=('documents.custommetadatafieldvalue',),
        ),
    ]
