# Generated by Django 3.1.7 on 2021-03-07 19:55

from django.db import migrations, models


def set_path(apps, schema_editor):
    Tag = apps.get_model('documents', 'Tag')
    i = 1
    for t in Tag.objects.order_by('name'):
        t.path = f"{i:04}"
        t.save()
        i += 1


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1014_auto_20210228_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='path',
            field=models.CharField(max_length=255, null=True, blank=True)
        ),
        migrations.RunPython(
            set_path,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='tag',
            name='path',
            field=models.CharField(max_length=255, unique=True)
        ),
    ]
